[app]
port = 9001
name = 'ws-center'
host = 'http://127.0.0.1:9001'

[redis]
host = '127.0.0.1'
port = 6379
password = ''
prefix = 'socket'

[socketIO]
pingTimeout = 40000
pingInterval = 5000
transports = ['websocket', 'polling']
path = '/ws'
